#NAME:	Matthew Chan
#EMAIL:	matthew_2185@yahoo.com
#ID:	805291212

default: dist

clean:
	rm -f *.tar.gz

dist:	clean
	tar -czvf lab4a-805291212.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
