#NAME:	Matthew Chan
#EMAIL:	matthew_2185@yahoo.com
#ID:	805291212


default:
	rm -f lab3b
	ln -s lab3b.py lab3b
	chmod u+x lab3b
clean:
	rm -f lab3b *.tar.gz
dist:
	tar -czvf lab3b-805291212.tar.gz lab3b.py Makefile README
