#NAME: 	Matthew Chan
#EMAIL:	matthew_2185@yahoo.com
#ID:	805291212

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

clean:
	rm -f lab3a *.tar.gz

dist:
	tar -czvf lab3a-805291212.tar.gz lab3a.c Makefile README ext2_fs.h
